cask_args appdir: "/Applications"
tap "caskroom/cask"
brew "git"
brew "hub"
brew "reattach-to-user-namespace"
brew "sourcery", args: ["HEAD"]
brew "swiftlint", args: ["HEAD"]
brew "tmux"
brew "vim"
brew "zsh"
cask "google-chrome"
cask "fastlane"
cask "flycut"
cask "gpg-suite"
cask "shiftit"
