cask_args appdir: "/Applications"
tap "bahdotsh/zp"
tap "facebook/fb"
tap "homebrew/aliases"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "rs/tap"
brew "chruby"
brew "chruby-fish"
brew "direnv"
brew "eza"
brew "fd"
brew "fish"
brew "fisher"
brew "fzy"
brew "git"
brew "git-delta"
brew "glow"
brew "hub"
brew "libhdhomerun"
brew "luajit", args: ['HEAD']
brew "mas"
brew "neovim", args: ['HEAD']
brew "node"
brew "ripgrep"
brew "ruby-install"
brew "tree-sitter", args: ['HEAD']
brew "unxip"
brew "xcinfo"
brew "zoxide"
cask "ankerwork"
cask "brave-browser"
cask "buildsettingextractor"
cask "clipy"
cask "copilot-for-xcode"
cask "deckset"
cask "docker"
cask "font-sf-mono"
cask "hdhomerun"
cask "mimestream"
cask "rectangle-pro"
cask "slack-beta"
cask "tuple"
cask "wezterm"
cask "xcodes"
cask "zoom"
mas "Pixelmator Pro", id: 1289583905
mas "Sourcery Pro", id: 1561780836
mas "Wipr", id: 1320666476
