from pathlib import Path
import re
import unittest


REPO_ROOT = Path(__file__).resolve().parents[4]
SKILLS_ROOT = REPO_ROOT / "codex" / "skills"
COMMANDS = (
    "--source|validate|open|prepare|record|execute|observe|state|close|decide|"
    "doctor|path|create|latest|init|capture|query|map|status|reopen|export|"
    "compact|handoff|show|migrate|recent|recall|codify-candidates|"
    "quality-audit|value-report|memory-digest|datasets|dataset-schema"
)
PROCEDURAL = re.compile(rf"(?<![\w$-])ledger\s+(?:{COMMANDS})\b")
PROCEDURAL_ARGV = re.compile(
    rf'''["']ledger["']\s*,\s*["'](?:{COMMANDS})["']'''
)
PROCEDURAL_EXEC = re.compile(r"(?<![\w$-])(?:command|exec)\s+ledger\b")

TEXT_SUFFIXES = {
    ".bash",
    ".json",
    ".md",
    ".py",
    ".sh",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
    ".zsh",
}

EXPECTED_CONSUMERS = {
    "actuating",
    "goal-actuating",
    "goal-contract",
    "goal-grind",
    "learnings",
    "negative-ledger",
    "plan",
    "review-fold",
    "synesthesia",
    "universalist",
}

DECLARATIVE_NATIVE_LINES = {
    (
        "codex/skills/actuating/SKILL.md",
        "`ledger --source actuation` is the only executable actuation gate. Do not invoke",
    ),
    (
        "codex/skills/actuating/SKILL.md",
        "unfolds and folds; `ledger --source actuation` never owns that recursion or",
    ),
    (
        "codex/skills/actuating/references/decision-contract.yaml",
        "cue_literals: [ledger --source actuation, closure-decision/v1, complete, ready-to-ship]",
    ),
    (
        "codex/skills/actuating/references/decision-contract.yaml",
        "executable_authority: ledger --source actuation",
    ),
    (
        "codex/skills/actuating/references/live-semantics.yaml",
        "executable_authority: ledger --source actuation",
    ),
    (
        "codex/skills/actuating/references/live-semantics.yaml",
        "statement: Every actuation transition and closure decision is produced by ledger --source actuation; no second-language gate participates.",
    ),
    (
        "codex/skills/goal-actuating/SKILL.md",
        "Inspect the projection before opening it. `ledger --source actuation` conserves",
    ),
    (
        "codex/skills/memory-source-notes/SKILL.md",
        "- `ledger --source learnings` owns `.ledger/learnings/events.jsonl` and the admission gate for learning snapshots.",
    ),
    (
        "codex/skills/memory-source-notes/SKILL.md",
        "- `ledger --source synesthesia` owns `.ledger/synesthesia/events.jsonl` and the canonical sensory mapping or activation-boundary event.",
    ),
    (
        "codex/skills/memory-source-notes/references/extension-payloads.md",
        "An active projection is admissible only when generated by `ledger export` from a valid ledger record.",
    ),
    (
        "codex/skills/negative-ledger/SKILL.md",
        "memory-note: not-attempted: ledger export unavailable",
    ),
}


def declarative_native_reference(path: Path, line: str) -> bool:
    return (path.as_posix(), line.strip()) in DECLARATIVE_NATIVE_LINES


def procedural_consumers():
    consumers = {}
    for skill_dir in SKILLS_ROOT.iterdir():
        if not skill_dir.is_dir() or skill_dir.name == "ledger":
            continue
        references = []
        for path in skill_dir.rglob("*"):
            if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
                continue
            for line_number, line in enumerate(path.read_text().splitlines(), start=1):
                relative_path = path.relative_to(REPO_ROOT)
                is_procedural = any(
                    pattern.search(line)
                    for pattern in (PROCEDURAL, PROCEDURAL_ARGV, PROCEDURAL_EXEC)
                )
                if is_procedural and not declarative_native_reference(relative_path, line):
                    references.append(f"{relative_path}:{line_number}:{line.strip()}")
        if references:
            consumers[skill_dir.name] = references
    return consumers


class ConsumerContractTests(unittest.TestCase):
    def test_every_procedural_consumer_declares_bootstrap(self):
        consumers = procedural_consumers()
        missing = []
        for skill_name, references in consumers.items():
            skill = SKILLS_ROOT / skill_name / "SKILL.md"
            if not skill.is_file() or "$ledger ensure" not in skill.read_text():
                missing.extend(references)

        self.assertEqual([], missing, "\n".join(missing))
        self.assertTrue(
            EXPECTED_CONSUMERS.issubset(consumers),
            EXPECTED_CONSUMERS - set(consumers),
        )

    def test_deprecated_per_invocation_mediation_is_absent(self):
        deprecated_skill_surface = "$ledger" + " run --"
        deprecated_script_path = "scripts/" + "ledger-runtime"
        old_wrapper = SKILLS_ROOT / "ledger" / "scripts" / "ledger-runtime"
        violations = []
        for path in SKILLS_ROOT.rglob("*"):
            if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
                continue
            if path == Path(__file__).resolve():
                continue
            for line_number, line in enumerate(path.read_text().splitlines(), start=1):
                if deprecated_skill_surface in line or deprecated_script_path in line:
                    relative_path = path.relative_to(REPO_ROOT)
                    violations.append(f"{relative_path}:{line_number}:{line.strip()}")

        self.assertEqual([], violations, "\n".join(violations))
        self.assertFalse(old_wrapper.exists(), old_wrapper)


if __name__ == "__main__":
    unittest.main()
