model = "gpt-5.4"
model_context_window = 1000000
model_auto_compact_token_limit = 900000
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
suppress_unstable_features_warning = true
web_search = "live"
personality = "pragmatic"
service_tier = "fast"

[agents]
max_threads = 96
max_depth = 3

[features]
unified_exec = true
steer = true
collaboration_modes = true
apps = true
personality = true
memories = true
sqlite = true
responses_websockets_v2 = true
multi_agent = true
multi_agent_v2 = true
prevent_idle_sleep = true
voice_transcription = true
realtime_conversation = true
js_repl = true
default_mode_request_user_input = true
fast_mode = true
codex_hooks = true

[tui]
experimental_mode = "execute"
status_line = ["current-dir", "git-branch", "context-remaining", "model-with-reasoning", "codex-version", "fast-mode", "session-id", "five-hour-limit", "weekly-limit"]
theme = "coldark-dark"
terminal_title = ["spinner", "project", "status", "thread", "task-progress"]

[notice]
hide_rate_limit_model_nudge = true

[projects."/Users/tk/workspace/tk/codex"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk/shift"]
trust_level = "trusted"

[projects."/Users/tk/.dotfiles"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk/skills-zig"]
trust_level = "trusted"

[projects."/Users/tk/Downloads"]
trust_level = "trusted"

[projects."/Users/tk/workspace/opencode-harness-gist"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk/nullclaw"]
trust_level = "trusted"

[projects."/Users/tk/workspace/art/interview/point"]
trust_level = "trusted"

[projects."/Users/tk/workspace/art/gamelan"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk"]
trust_level = "trusted"
