#!/usr/bin/env bash
# boundary_validator_scaffold.sh — emit a boundary validator for external input.
#
# Use when refactoring a boundary (HTTP handler, CLI arg parser, file reader,
# queue consumer) to eliminate `any` / `as any` propagation downstream (P15).
#
# Usage: boundary_validator_scaffold.sh <lang> <type_name> [output_file]
#   lang: ts | python | rust
#
# Emits a ready-to-edit validator skeleton per TYPE-SHRINKS.md.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  cat <<EOF
Usage: $0 <lang> <type_name> [output_file]
  lang: ts | python | rust
Examples:
  $0 ts Order src/validators/order.ts
  $0 python Order src/validators/order.py
  $0 rust Order src/validators/order.rs
EOF
  exit 2
fi

LANG="$1"
TYPE="$2"
OUT="${3:-}"
LOWER=$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')

case "$LANG" in
  ts)
    OUT="${OUT:-src/validators/${LOWER}.ts}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<TS
// Boundary validator for ${TYPE} — generated by simplify-and-refactor-code-isomorphically
// See references/TYPE-SHRINKS.md and VIBE-CODED-PATHOLOGIES.md P15.
//
// Install: pnpm add zod

import { z } from 'zod';

export const ${TYPE}Schema = z.object({
  // TODO: fill fields with validators
  id: z.string(),
  // createdAt: z.coerce.date(),
  // amount: z.number().int().positive(),
  // status: z.enum(['pending', 'shipped', 'cancelled']),
});

export type ${TYPE} = z.infer<typeof ${TYPE}Schema>;

/** Parse, throwing ZodError on invalid input. Callers downstream see a fully-typed ${TYPE}. */
export function parse${TYPE}(input: unknown): ${TYPE} {
  return ${TYPE}Schema.parse(input);
}

/** Safe parse, returning Result-ish. */
export function tryParse${TYPE}(input: unknown):
  | { ok: true; value: ${TYPE} }
  | { ok: false; error: z.ZodError }
{
  const r = ${TYPE}Schema.safeParse(input);
  return r.success ? { ok: true, value: r.data } : { ok: false, error: r.error };
}

// Use at your boundaries:
//   app.post('/api/orders', async (req) => {
//     const order = parse${TYPE}(req.body);   // typed downstream
//     return createOrder(order);
//   });
TS
    ;;

  python)
    OUT="${OUT:-src/validators/${LOWER}.py}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<PY
"""Boundary validator for ${TYPE} — generated by simplify-and-refactor-code-isomorphically.

See references/TYPE-SHRINKS.md and VIBE-CODED-PATHOLOGIES.md P15.

Install: pip install pydantic
"""

from __future__ import annotations

from pydantic import BaseModel, Field, ValidationError
from typing import Literal


class ${TYPE}(BaseModel):
    """Validated ${TYPE}. Use at boundaries (API handlers, queue consumers, file readers)."""
    model_config = {"frozen": True, "extra": "forbid"}

    id: str
    # TODO: fill remaining fields
    # created_at: datetime
    # amount: int = Field(gt=0)
    # status: Literal["pending", "shipped", "cancelled"]


def parse_${LOWER}(raw: dict | str | bytes) -> ${TYPE}:
    """Parse raw input to ${TYPE}. Raises pydantic.ValidationError on invalid input."""
    if isinstance(raw, (str, bytes)):
        return ${TYPE}.model_validate_json(raw)
    return ${TYPE}.model_validate(raw)


def try_parse_${LOWER}(raw: dict | str | bytes) -> tuple[${TYPE} | None, ValidationError | None]:
    """Safe parse. Returns (instance, None) or (None, error)."""
    try:
        return parse_${LOWER}(raw), None
    except ValidationError as e:
        return None, e


# Use at your boundaries:
#   @app.post("/api/orders")
#   async def create_order(request: Request) -> Response:
#       order = parse_${LOWER}(await request.body())  # typed downstream
#       return await store(order)
PY
    ;;

  rust)
    OUT="${OUT:-src/validators/${LOWER}.rs}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<RUST
// Boundary validator for ${TYPE} — generated by simplify-and-refactor-code-isomorphically
// See references/TYPE-SHRINKS.md and VIBE-CODED-PATHOLOGIES.md P15.
//
// Cargo.toml additions:
//   serde = { version = "1", features = ["derive"] }
//   thiserror = "1"
//   validator = { version = "0.19", features = ["derive"] }   # optional

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ${TYPE} {
    pub id: String,
    // TODO: fill remaining fields
    // #[serde(rename = "createdAt")]
    // pub created_at: chrono::DateTime<chrono::Utc>,
    // pub amount: i64,
    // pub status: ${TYPE}Status,
}

// #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
// #[serde(rename_all = "snake_case")]
// pub enum ${TYPE}Status { Pending, Shipped, Cancelled }

#[derive(Debug, Error)]
pub enum Parse${TYPE}Error {
    #[error("invalid JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error("invariant violated: {0}")]
    Invariant(String),
}

impl ${TYPE} {
    /// Parse and validate invariants. Use at boundaries.
    pub fn parse(raw: &[u8]) -> Result<Self, Parse${TYPE}Error> {
        let parsed: Self = serde_json::from_slice(raw)?;
        parsed.check_invariants()?;
        Ok(parsed)
    }

    fn check_invariants(&self) -> Result<(), Parse${TYPE}Error> {
        if self.id.is_empty() {
            return Err(Parse${TYPE}Error::Invariant("id must not be empty".into()));
        }
        // TODO: add more invariants
        Ok(())
    }
}

// Use at your boundaries:
//   async fn handler(body: Vec<u8>) -> Result<Json<Order>, AppError> {
//       let order = Order::parse(&body)?;   // typed downstream
//       Ok(Json(store(order).await?))
//   }
RUST
    ;;

  *)
    echo "Unsupported lang: $LANG. Supported: ts, python, rust" >&2
    exit 2
    ;;
esac

echo "wrote $OUT"
echo ""
echo "Next:"
echo "  1. Fill in the TODO fields matching your real type shape."
echo "  2. Adopt the validator at each boundary:"
case "$LANG" in
  ts)     echo "     rg 'JSON\\.parse|req\\.body|as any' src/ -n   # find boundaries to migrate" ;;
  python) echo "     rg 'json\\.loads|request\\.json|Any' src/ -n" ;;
  rust)   echo "     rg 'serde_json::from_str|unwrap' src/ -n" ;;
esac
echo "  3. Each migration is one commit with an isomorphism card."
echo "  4. Downstream code becomes ${LANG}-typed; any/Unknown propagation stops."
