#!/usr/bin/env bash
# property_test_scaffold.sh — emit a property-based test skeleton.
#
# Usage: property_test_scaffold.sh <lang> <function_name> [output_file]
#   lang: rust | ts | python | go
#
# Writes a ready-to-edit property test file per conventions in PROPERTY-TESTS.md.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  cat <<EOF
Usage: $0 <lang> <function_name> [output_file]
  lang: rust | ts | python | go
Examples:
  $0 rust normalize tests/prop_normalize.rs
  $0 ts parseOrder src/parseOrder.prop.test.ts
  $0 python normalize tests/test_normalize_prop.py
  $0 go Max internal/cmp/cmp_prop_test.go
EOF
  exit 2
fi

LANG="$1"
FN="$2"
OUT="${3:-}"

case "$LANG" in
  rust)
    OUT="${OUT:-tests/prop_${FN}.rs}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<RUST
// Property tests for ${FN} — generated by simplify-and-refactor-code-isomorphically
// See references/PROPERTY-TESTS.md
//
// Add to Cargo.toml [dev-dependencies]:
//   proptest = "1"

use proptest::prelude::*;
// use your_crate::${FN};

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1000))]

    /// Determinism: same input → same output
    #[test]
    fn ${FN}_deterministic(input in any::<String>()) {
        // prop_assert_eq!(${FN}(&input), ${FN}(&input));
    }

    /// Idempotence: applying twice equals applying once
    #[test]
    fn ${FN}_idempotent(input in any::<String>()) {
        // let a = ${FN}(&input);
        // prop_assert_eq!(${FN}(&a), a);
    }

    /// Round-trip (if applicable): encode then decode == original
    #[test]
    fn ${FN}_round_trip(input in any::<String>()) {
        // let encoded = encode(&input);
        // let back = ${FN}(&encoded);
        // prop_assert_eq!(back, input);
    }

    /// Oracle: new impl matches reference impl on random inputs
    #[test]
    fn ${FN}_matches_reference(input in any::<String>()) {
        // prop_assert_eq!(${FN}_new(&input), ${FN}_reference(&input));
    }
}
RUST
    ;;

  ts)
    OUT="${OUT:-src/${FN}.prop.test.ts}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<TS
// Property tests for ${FN} — generated by simplify-and-refactor-code-isomorphically
// See references/PROPERTY-TESTS.md
//
// Install: pnpm add -D fast-check vitest (or jest)

import { describe, test } from 'vitest';
import * as fc from 'fast-check';
// import { ${FN} } from './${FN}';

describe('${FN} properties', () => {
  test('deterministic: same input → same output', () => {
    fc.assert(fc.property(fc.string(), (s) => {
      // expect(${FN}(s)).toEqual(${FN}(s));
    }), { numRuns: 1000 });
  });

  test('idempotent: ${FN}(${FN}(x)) === ${FN}(x)', () => {
    fc.assert(fc.property(fc.string(), (s) => {
      // const a = ${FN}(s);
      // expect(${FN}(a)).toEqual(a);
    }));
  });

  test('round-trip: decode(encode(x)) === x', () => {
    fc.assert(fc.property(fc.anything(), (x) => {
      // expect(${FN}(encode(x))).toEqual(x);
    }));
  });

  test('oracle: new matches reference', () => {
    fc.assert(fc.property(fc.string(), (s) => {
      // expect(${FN}New(s)).toEqual(${FN}Reference(s));
    }));
  });
});
TS
    ;;

  python)
    OUT="${OUT:-tests/test_${FN}_prop.py}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<PY
# Property tests for ${FN} — generated by simplify-and-refactor-code-isomorphically
# See references/PROPERTY-TESTS.md
#
# Install: pip install hypothesis pytest

from hypothesis import given, settings, strategies as st
# from mymodule import ${FN}


@given(st.text())
@settings(max_examples=1000)
def test_${FN}_deterministic(s):
    """Same input → same output."""
    # assert ${FN}(s) == ${FN}(s)
    pass


@given(st.text())
def test_${FN}_idempotent(s):
    """Applying twice equals applying once."""
    # a = ${FN}(s)
    # assert ${FN}(a) == a
    pass


@given(st.lists(st.integers()))
def test_${FN}_round_trip(xs):
    """decode(encode(x)) == x."""
    # assert ${FN}(encode(xs)) == xs
    pass


@given(st.text())
def test_${FN}_matches_reference(s):
    """Oracle: new impl matches reference impl."""
    # assert ${FN}_new(s) == ${FN}_reference(s)
    pass
PY
    ;;

  go)
    OUT="${OUT:-$(dirname "$(pwd)")/${FN}_prop_test.go}"
    mkdir -p "$(dirname "$OUT")"
    cat > "$OUT" <<GO
// Property tests for ${FN} — generated by simplify-and-refactor-code-isomorphically
// See references/PROPERTY-TESTS.md
//
// Install: go get github.com/leanovate/gopter

package yourpkg

import (
	"testing"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
)

func Test${FN}Properties(t *testing.T) {
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 1000
	p := gopter.NewProperties(parameters)

	p.Property("${FN} is deterministic", prop.ForAll(
		func(s string) bool {
			// return ${FN}(s) == ${FN}(s)
			return true
		},
		gen.AnyString(),
	))

	p.Property("${FN} is idempotent", prop.ForAll(
		func(s string) bool {
			// a := ${FN}(s)
			// return ${FN}(a) == a
			return true
		},
		gen.AnyString(),
	))

	p.TestingRun(t)
}
GO
    ;;

  *)
    echo "Unsupported lang: $LANG. Supported: rust, ts, python, go" >&2
    exit 2
    ;;
esac

echo "wrote $OUT"
echo ""
echo "Next: fill in the commented lines with your real function, then run:"
case "$LANG" in
  rust)   echo "  cargo test --test $(basename "$OUT" .rs)" ;;
  ts)     echo "  pnpm vitest run $OUT" ;;
  python) echo "  pytest $OUT -v" ;;
  go)     echo "  go test -run Test${FN}Properties ./..." ;;
esac
